name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "25 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: kaz004
      - name: Commit generated graph
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update 3D contribution graph
          file_pattern: profile-3d-contrib/*.svg
